[package]
name = "bind"
version = "0.1.0"
authors = ["Gérald Lelong <gerald.lelong@easymov.fr>"]
edition = "2018"
license = "ISC"
description = "Generates bindings to clipper"

[dependencies]
bindgen = "0.55.1"
